CREATE DATABASE CLIENTE_TAREFA

GO

USE CLIENTE_TAREFA

GO

CREATE TABLE CLIENTE 
(ID INT IDENTITY(1,1) PRIMARY KEY,NOME NVARCHAR(50))

GO

CREATE TABLE TAREFA
 (ID INT IDENTITY(1,1) PRIMARY KEY,
 ID_CLIENTE INT NOT NULL,
DATA_CRIACAO DATETIME,
DESCRICAO NVARCHAR(80),
  CONSTRAINT FK_ID_CLIENTE FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTE(ID))
  

GO